name: meow
description: "猫猫图鉴"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # iOS风格图标库
  cupertino_icons: ^1.0.8
  # 矢量图加载组件
  flutter_svg: ^2.2.3
  # 网络请求库
  dio: ^5.9.0
  # 状态管理
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  # 路由管理
  go_router: ^17.0.1
  # 本地存储
  shared_preferences: ^2.5.4
  # 图片选择器
  image_picker: ^1.2.1
  # JSON 序列化
  json_annotation: ^4.9.0
  flutter_web_auth_2: ^5.0.3
  # 摘要/签名（COS 上传签名）
  crypto: ^3.0.0
  # flutter_secure_storage: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # 代码规范
  flutter_lints: ^6.0.0

  # 代码生成
  build_runner: ^2.10.5
  riverpod_generator: ^4.0.0+1
  # JSON 序列化
  json_serializable: ^6.11.2
  # 应用图标生成
  flutter_launcher_icons: ^0.14.4
  # 启动页配置
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/猫猫图鉴-logo.png"  # 图标路径
  adaptive_icon_background: "#FFFFFF"  # Android 适应性图标背景色

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: '#FFFFFF'

  fullscreen: true

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # 加载资源
  assets:
    - assets/images/
    - assets/icons/
